name: deploy-shiny
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::pkgload 
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
      - name: Push to shiny.io
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: export SHINY_ACC_NAME=${{secrets.SHINY_ACC_NAME}} && export TOKEN=${{secrets.TOKEN}} && export SECRET=${{secrets.SECRET}} && Rscript --no-save deploy.R
  
