name: deploy App
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:   
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install packages
        run: |
          sudo apt install -y libcurl4-openssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libssl-dev libmagick++-dev libv8-dev  libnode-dev libudunits2-dev libgdal-dev libprotobuf-dev libjq-dev protobuf-compiler libprotobuf-dev libprotoc-dev libpoppler-cpp-dev libarchive-dev
          Rscript -e "install.packages('usethis', dependencies=TRUE)"
          Rscript -e "install.packages('rsconnect')"
      - name: Deploy
        run: echo "SHINY_ACC_NAME= ${{secrets.SHINY_ACC_NAME}}\nTOKEN=${{secrets.TOKEN}}\nSECRET=${{secrets.SECRET}}" > .Renviron && Rscript deploy.R
 
