# This is a basic workflow that is manually triggered

name: deploy-shiny
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
      - name: Push to shiny.io 
        run: | 
          Rscript -e "rsconnect::setAccountInfo(name=${{secrets.SHINY_ACC_NAME}}, token=${{secrets.TOKEN}}, secret=${{secrets.SECRET}})" 
          Rscript -e "rsconnect::deployApp(appName = 'daneApp')
